apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:  # Controle da Replica
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
      spec:  # Definicao do POD
        containers:
        - name: nginx-container
          image: nginx
replicas: 3
        
